<?php
/* @var $this \App\View\Layout\DefaultLayout */
$this->addJs(array(
    $this->themeUrl() . '/js/views/newsCtrl.js',
));
?>

<style>
    #modalEdit .modal-body{padding: 0;}
    #modalEdit .tab-content{padding: 15px;}
    #modalEdit legend{margin-bottom: 0;}
</style>

<div id="page-title">
    <h1 class="page-header text-overflow">Tin Tức</h1>
    <div class="col-sm-2 alert alert-success" id="notify" style="z-index:1000">
        <span>Thành Công !!!</span>
    </div>
</div>

<angular ng-cloak ng-controller="NewsCtrl">
    <div class="panel">
        <div class="panel-body">
            <button class="btn btn-primary btn-labeled fa fa-plus" ng-click="edit()">Thêm mới</button>
            <button class="btn btn-default" ng-click="delete()" ng-disabled="getChecked().length == 0">Xóa</button>
            <form action="action" class="form-group" style="float:right">
                <label class="control-label" style="z-index:1"><strong>Category</strong></label>
                <select ng-model="sltFilter">
                    <option value="">Tất Cả</option>
                    <option ng-repeat="cate in Categories">{{cate.name}}</option>
                </select>
            </form>
            <table class="table table-striped table-hover table-record">
                <thead>
                    <tr>
                        <th style="min-width: 50px;" class="center">
                            <input type="checkbox" />
                        </th>
                        <th style="min-width: 50px;" class="center">&nbsp;</th>
                        <th style="min-width: 50px;" class="center">STT</th>
                        <th style="min-width: 150px;" class="center">Image</th>
                        <th style="min-width: 150px;" class="center">Category</th>
                        <th style="min-width: 150px;" class="center">Title</th>
                        <th style="min-width: 150px;" class="center">Intro</th>
                        <th style="min-width: 150px;" class="center">Content</th>
                        <th style="min-width: 150px;" class="center">Date Create</th>
                    </tr>
                </thead>
                <tbody>
                    <tr ng-repeat="(key,news) in News | filter: sltFilter" ng-click="news.id = !news.id">
                        <td class="center">
                            <input type="checkbox"  ng-model="news.id" ng-click="$event.stopPropagation()"/>
                        </td>
                        <td class="tbl-actions center">
                            <div class="dropdown">
                                <a href="javascript:;" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-bars"></i></a>
                                <ul class="dropdown-menu">
                                    <li><a href="javascript:;" ng-click="edit(news)">Sửa</a></li>
                                    <li><a href="javascript:;" ng-click="delete(news.id)">Xóa</a></li>
                                </ul>
                            </div>
                        </td>
                        <td class="center">{{key + 1}}</td>
                        <td class="center"><img ng-src="<?php echo url() . '/'; ?>{{news.iurl}}" id="imgNews" style="align-items: center"></td>
                        <td class="center">{{news.name}}</td>
                        <td class="center">{{news.title}}</td>
                        <td class="center">{{news.intro.substr(0, 50)}}</td>
                        <td class="center" ng-bind-html="news.content.substr(0, 100)"></td>
                        <td class="center">{{news.formatTime}}</td>
                    </tr>
                </tbody>
            </table>
        </div><!--panel-body-->
    </div><!--panel-->


    <form class="form-horizontal" id="form-edit">
        <!-- Modal -->
        <div class="modal fade" id="modalEdit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" ng-dom="modalEdit">
            <div class="modal-dialog model-news" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Tin Tức</h4>
                    </div>
                    <div class="modal-body">
                        <div class="tab-content">
                            <div class="form-group">
                                <div  class="tab-pane">
                                    <div class="form-group">
                                        <label class="control-label col-xs-2" for="txt-name"><?php echo static::HTML_REQUIRED ?> Category:</label>
                                        <div class="col-xs-8">
                                            <select class="control-label col-xs-5" name="slCategories" id="slCategories" ng-model="editing.name">
                                                <option value="">Chọn Loại Tin</option>
                                                <option ng-repeat="cate in Categories">{{cate.name}}</option>
                                            </select>
                                        </div>  
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-xs-2" for="txt-code"><?php echo static::HTML_REQUIRED ?> Title:</label>
                                        <div class="col-xs-9">
                                            <input type="text" id="txt-code" name="txtTitle" ng-model="editing.title" required class="form-control" placeholder="Title">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-xs-2" for="txt-name"><?php echo static::HTML_REQUIRED ?> Intro:</label>
                                        <div class="col-xs-9">
                                            <textarea class="form-control" rows="3" id="comment" placeholder="Intro" name="txtIntro" ng-model="editing.intro"></textarea>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-xs-2" for="txt-name"><?php echo static::HTML_REQUIRED ?> Content:</label>
                                        <div class="col-xs-9">
                                            <div ng-cloak ng-show="isReady" class="showContent">
                                                <textarea ckeditor="editorOptions" name="txtContent" id="txtContent" ng-model="editing.content"></textarea>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-xs-2" for="txt-name"><?php echo static::HTML_REQUIRED ?> Image:</label>
                                        <div class="col-xs-9" id="box-upload-file">
                                            <a href="#" ng-click="uploadFile()" title="Đính kèm File" class="pull-left"><i class="fa fa-upload"></i>UpLoad</a>
                                            <input style="display: none;" type="file" name="fileReqUpload" id="fileReqUpload" multiple accept="image/gif,image/png,image/jpeg,image/jpg">
                                            <img ng-src="<?php echo url() . '/' ?>{{editing.iurl}}" id="imgNews">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Hủy bỏ</button>
                        <button type="button" class="btn btn-primary" ng-click="save()" ng-disabled="ajax.save">Ghi lại</button>
                        <div class="form-group">
                            <div class="col-xs-8 col-xs-offset-4">
                                <label class="check" id="chkCheck">
                                    <input type="checkbox"  ng-model="chkCheck"/>
                                    Ghi&Thêm Lại
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>

    <div ng-user-picker></div>
</angular>

