<?php
$this->addJs(array(
    $this->themeUrl() . '/js/detailNews.js'
));
?>
<script>
    var idDetail = <?php echo $data['id']; ?>
</script>
<angular ng-controller="detailCtrl">
    <div id="content">
        <div id="con-right">
            <h2 style="color: #81b300" class="ng-cloak">{{detailNews.title}}</h2>
            <div class="baiviet-ngay ng-cloak">{{detailNews.cretedDate}}</div>
            <div class="baiviet-sukien">Chuyên Mục:
                <h3><a title="" href="" class="ng-cloak">{{detailNews.name}}</a></h3>
            </div>
            <h2>
                <p class="baiviet-sapo ng-cloak" style="font-size: 25px;">
                    {{detailNews.intro}}
                </p>
            </h2><br>
            <div ng-bind-html="detailNews.content" class="ng-cloak">

            </div>
        </div>
        <div id="con-left">
            <div class="show-newslike">Tin tức xem nhiều</div>
            <ul>
                <li ng-repeat="x in listNews">
                    <span class="imgFloat-tttt imgNews-home">
                        <a href="<?php echo url('/detail/') ?>{{x.id}}" title="">
                            <img style="margin:2px 0px" ng-src="<?php echo url() . '/'; ?>{{x.iurl}}" width="90" height="70" alt="" class="ng-cloak">
                        </a>  
                    </span>
                    <span class="news-title" style="padding-top:10px">
                        <a href="<?php echo url('/detail/') ?>{{x.id}}" class="ng-cloak">{{x.title}}</a>
                    </span>
                </li>
            </ul>

        </div>
    </div>
</angular>
