<?php
$this->addJs(array(
    $this->themeUrl() . '/js/homePage.js',
));
?>
<angular ng-controller="homeCtrl">
    <!-------------------->

    <div id="show-news">
        <div class="title_box">
            <a href="#" id="link-cate">Tin mới nhất</a>
        </div>
        <ul>
            <li ng-repeat="x in listNews">
                <div id="c-image"  ng-click="detail(x.id)">
                    <a href="<?php echo url('/detail/') ?>{{x.id}}"><img ng-src="<?php echo url() . '/'; ?>{{x.iurl}}" alt="" class="ng-cloak"></a>
                </div>
                <div id="c-content">
                    <a href="<?php echo url('/detail/') ?>{{x.id}}" ng-click="detail(x.id)" class="ng-cloak">{{x.title}}</a>  
                </div>
            </li>  
        </ul>
    </div>
    <div id="show-news">
        <div class="title_box">
            <a href="#" id="link-cate">Tin xem nhiều</a>
        </div>
        <ul>
            <li ng-repeat="x in listNewsLike">
                <div id="c-image"  ng-click="detail(x.id)">
                    <a href="<?php echo url('/detail/') ?>{{x.id}}"><img ng-src="<?php echo url() . '/'; ?>{{x.iurl}}" alt="" class="ng-cloak"></a>
                </div>
                <div id="c-content">
                    <a href="<?php echo url('/detail/') ?>{{x.id}}" ng-click="detail(x.id)" class="ng-cloak">{{x.title}}</a>  
                </div>
            </li> 
        </ul>
    </div>
</angular>






