<?php
$this->addJs(array(
    $this->themeUrl() . '/js/search.js'
));
?>
<script>
    var txtSearch = '<?php echo $data['txtSearch'];?>';
</script>
<angular ng-controller="searchCtrl">
    <div id="content">
        <div id="con-right">
            <div id="show-category">
                <div class="show-newslike">Kết quả tìm kiếm </div>
                <ul>
                    <li class="ng-scope" ng-repeat="x in listSearch">
                        <a href="<?php echo url('/detail/') ?>{{x.id}}" class="ng-binding ng-cloak">{{x.title}}</a>
                        <span class="imgFloat-tttt imgCategory">
                            <a href="<?php echo url('/detail/') ?>{{x.id}}" title="">
                                <img style="margin:2px 0px" ng-src="<?php echo url() . '/'; ?>{{x.iurl}}">
                            </a>  
                        </span>
                        <span class="news-title ng-cloak">
                           {{x.intro.substr(0, 150)}}
                        </span>
                    </li>
                </ul>
            </div>
        </div>
    </div> 
</div>
</div>
</angular>


